apiVersion: v1
kind: Service
metadata:
  name: typescript-app-service-prod
spec:
  selector:
    app: typescript-app-prod 
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 3000
  type: LoadBalancer
