apiVersion: v1
kind: Service
metadata:
  name: typescript-app-service
spec:
  selector:
    app: typescript-app 
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 3000
  type: LoadBalancer
